import { getKeys } from "../../libs/utility.mjs";
import type { CharacterSetting } from "../../setting-define.mjs";
import {
  characterTable,
  type CharacterKey,
} from "../characters/characters.mjs";

export type CharactersPresetKey = `baseCharacters` | `default` | CharacterKey;

export type CharactersPreset = Record<CharactersPresetKey, CharacterSetting[]>;

const monoCharacterPresetsMap = Object.fromEntries(
  getKeys(characterTable).reduce(
    (acc, key) => acc.set(key, [{ key }]),
    new Map<CharacterKey, CharacterSetting[]>(),
  ),
) as Record<CharacterKey, CharacterSetting[]>;

const baseCharactersPreset = [
  { key: `blend-s-kaho-ibukimakisiko` },
  { key: `blue-archive-arona-ibukimakisiko` },
  { key: `blue-archive-yuuka-ibukimakisiko` },
  { key: `boufuri-maple-ibukimakisiko` },
  { key: `boufuri-sally-ibukimakisiko` },
  // { key: `boufuri-sally-king-dong` },
  { key: `danmachi-aiz-eternal2kpp` },
  { key: `danmachi-eina-eternal2kpp` },
  { key: `danmachi-haruhime-eternal2kpp` },
  { key: `danmachi-hestia-eternal2kpp` },
  { key: `danmachi-lili-eternal2kpp` },
  { key: `danmachi-ryu-eternal2kpp` },
  { key: `eromanga-sensei-elf-eternal2kpp` },
  { key: `eromanga-sensei-megumi-eternal2kpp` },
  { key: `eromanga-sensei-muramasa-little-jelly` },
  { key: `eromanga-sensei-sagiri-eternal2kpp` },
  { key: `eromanga-sensei-tomoe-little-jelly` },
  { key: `fate-rin-little-jelly` },
  { key: `futoku-no-guild-enome-zedotasco` },
  { key: `futoku-no-guild-tokishikko-ibukimakisiko` },
  { key: `goblin-slayer-cow-girl-eternal2kpp` },
  { key: `goblin-slayer-priestess-eternal2kpp` },
  { key: `higehiro-sayu-nochekaiser` },
  { key: `hyouka-eru-chenkin` },
  { key: `is-cecilia-nochekaiser` },
  { key: `is-charlotte-nochekaiser` },
  { key: `is-houki-nochekaiser` },
  { key: `is-laura-nochekaiser` },
  { key: `is-lingyin-nochekaiser` },
  { key: `is-tatenashi-nochekaiser` },
  { key: `isekai-nonbiri-nouka-ann-little-jelly` },
  { key: `isekai-nonbiri-nouka-hakuren-little-jelly` },
  { key: `isekai-nonbiri-nouka-ria-little-jelly` },
  { key: `isekai-nonbiri-nouka-rurushi-little-jelly` },
  { key: `isekai-nonbiri-nouka-tia-little-jelly` },
  { key: `isekai-ojisan-alicia-nochekaiser` },
  { key: `isekai-ojisan-mabel-nochekaiser` },
  { key: `isekai-ojisan-sui-nochekaiser` },
  { key: `isekai-ojisan-sumika-nochekaiser` },
  { key: `kagejitsu-alpha-nochekaiser` },
  { key: `kagejitsu-beta-nochekaiser` },
  { key: `kaguya-sama-ai-nochekaiser` },
  { key: `kaguya-sama-chika-eternal2kpp` },
  { key: `kaguya-sama-kaguya-eternal2kpp` },
  { key: `kaguya-sama-miko-nochekaiser` },
  { key: `konosuba-megumin-no-lora` },
  { key: `konosuba-yunyun-no-lora` },
  { key: `lycoris-recoil-chisato-nochekaiser` },
  { key: `lycoris-recoil-takina-nochekaiser` },
  { key: `machikado-mazoku-shamiko-ibukimakisiko` },
  { key: `mahoako-matama-notekaga` },
  { key: `majo-no-tabitabi-elaina-ibukimakisiko` },
  { key: `mushoku-tensei-aisha-ibukimakisiko` },
  { key: `mushoku-tensei-norn-ibukimakisiko` },
  { key: `mushoku-tensei-sylphiette-little-jelly` },
  { key: `mushoku-tensei-roxy-ibukimakisiko` },
  { key: "new-game-aoba-eternal2kpp" },
  { key: "new-game-hajime-eternal2kpp" },
  { key: "new-game-hifumi-eternal2kpp" },
  { key: "new-game-kou-eternal2kpp" },
  { key: "new-game-nene-eternal2kpp" },
  { key: "new-game-rin-eternal2kpp" },
  { key: "new-game-yun-eternal2kpp" },
  { key: `non-non-biyori-hotaru-notekaga` },
  { key: `ochifuru-hayu-enter` },
  { key: `ochifuru-hemo-enter` },
  { key: `ochifuru-ino-enter` },
  { key: `ochifuru-nina-enter` },
  { key: `ochifuru-roko-enter` },
  { key: `ochifuru-tone-enter` },
  { key: `prisma-illya-illya-flujoru` },
  { key: `re-zero-emilia-eternal2kpp` },
  { key: `re-zero-ram-eternal2kpp` },
  { key: `re-zero-rem-eternal2kpp` },
  { key: `rokudenashi-rumia-little-jelly` },
  { key: `ryuuou-hinatsuru-ai-ibukimakisiko` },
  { key: `ryuuou-yashajin-ai-ibukimakisiko` },
  { key: `sasuoni-honoka-nochekaiser` },
  { key: `sasuoni-mizuki-nochekaiser` },
  { key: `seirei-celia-ibukimakisiko` },
  { key: `slow-loop-hiyori-ibukimakisiko` },
  { key: `slow-loop-koharu-ibukimakisiko` },
  { key: `slow-loop-koi-ibukimakisiko` },
  { key: `spy-family-yor-eternal2kpp` },
  { key: `strike-witches-yoshika-gwess` },
  { key: `tenshi-sama-mahiru-jibunsagasinotabi` },
  { key: `tenshi-tsuki-noel-eternal2kpp` },
  { key: `tenshi-tsuki-towa-eternal2kpp` },
  { key: `tenshi-tsuki-tsumugi-eternal2kpp` },
  { key: `to-love-ru-haruna-nochekaiser` },
  { key: `to-love-ru-lala-nochekaiser` },
  { key: `to-love-ru-momo-lancelot`, probability: 0.5 },
  { key: `to-love-ru-momo-nochekaiser`, probability: 0.5 },
  { key: `to-love-ru-nana-lancelot`, probability: 0.5 },
  { key: `to-love-ru-nana-nochekaiser`, probability: 0.5 },
  { key: `to-love-ru-tearju-nochekaiser` },
  { key: `to-love-ru-yami-nochekaiser` },
  { key: `to-love-ru-yui-nochekaiser` },
  { key: `working-popura-ibukimakisiko` },
] as const satisfies CharacterSetting[];

const defaultPreset = [
  ...baseCharactersPreset,
  { key: `blend-s-kaho-ibukimakisiko-double-bun`, probability: 0.2 },
  { key: `blue-archive-yuuka-gym-ibukimakisiko`, probability: 0.2 },
  { key: `machikado-mazoku-shamiko-ponytail-ibukimakisiko`, probability: 0.2 },
  { key: `majo-no-tabitabi-elaina-no-ahoge-ibukimakisiko`, probability: 0.2 },
  { key: `mushoku-tensei-roxy-adventurer-ibukimakisiko`, probability: 0.05 },
  {
    key: `mushoku-tensei-roxy-adventurer-no-ahoge-ibukimakisiko`,
    probability: 0.05,
  },
  { key: `mushoku-tensei-roxy-hair-down-ibukimakisiko`, probability: 0.05 },
  { key: `mushoku-tensei-roxy-no-ahoge-ibukimakisiko`, probability: 0.05 },
  { key: `mushoku-tensei-roxy-pajamas-ibukimakisiko`, probability: 0.05 },
  { key: `ochifuru-hayu-idol-ribbon-enter`, probability: 0.2 },
  { key: `ochifuru-hemo-idol-ribbon-enter`, probability: 0.2 },
  { key: `ochifuru-ino-idol-ribbon-enter`, probability: 0.2 },
  { key: `ochifuru-nina-idol-ribbon-enter`, probability: 0.2 },
  { key: `ochifuru-roko-idol-ribbon-enter`, probability: 0.2 },
  { key: `spy-family-yor-eternal2kpp-thorn-princess`, probability: 0.2 },
  { key: `strike-witches-yoshika-witch-gwess`, probability: 0.2 },
  { key: `to-love-ru-tearju-low-tied-long-hair-nochekaiser`, probability: 0.2 },
] as const satisfies CharacterSetting[];

export const charactersPreset: CharactersPreset = {
  ...monoCharacterPresetsMap,

  baseCharacters: baseCharactersPreset,
  default: defaultPreset,
} as const;
