import type { HairTag } from "../tag-defines/hair.mjs";
import type { Visibility } from "../visibility.mjs";

const preset = {
  hair: {
    frontHead: true,
    sideHead: true,
    backHead: true,
    frontBreast: false,
    sideBreast: false,
    backBreast: false,
    frontMidriff: false,
    sideMidriff: false,
    backMidriff: false,
    frontHipAndThigh: false,
    sideHipAndThigh: false,
    backHipAndThigh: false,
    foot: false,
    wristAndHand: false,
    aroundBody: false,
  },
  bangs: {
    frontHead: true,
    sideHead: false,
    backHead: false,
    frontBreast: false,
    sideBreast: false,
    backBreast: false,
    frontMidriff: false,
    sideMidriff: false,
    backMidriff: false,
    frontHipAndThigh: false,
    sideHipAndThigh: false,
    backHipAndThigh: false,
    foot: false,
    wristAndHand: false,
    aroundBody: false,
  },
} as const satisfies Record<string, Visibility>;

const allHairColorVisibilities = {
  "aqua hair": preset.hair,
  "black hair": preset.hair,
  "blonde hair": preset.hair,
  "blue hair": preset.hair,
  "brown hair": preset.hair,
  "dark blue hair": preset.hair,
  "dark green hair": preset.hair,
  "green hair": preset.hair,
  "grey hair": preset.hair,
  "light blue hair": preset.hair,
  "light brown hair": preset.hair,
  "light green hair": preset.hair,
  "light purple hair": preset.hair,
  "multicolored hair": preset.hair,
  "orange hair": preset.hair,
  "pink hair": preset.hair,
  "purple hair": preset.hair,
  "red hair": preset.hair,
  "streaked hair": preset.hair,
  "two-tone hair": preset.hair,
  "white hair": preset.hair,
} as const satisfies Partial<Record<HairTag, Visibility>>;

const allHairLengthVisibilities = {
  "short hair": preset.hair,
  "medium hair": preset.hair,
  "long hair": preset.hair,
  "very long hair": preset.hair,
  "absurdly long hair": preset.hair,
} as const satisfies Partial<Record<HairTag, Visibility>>;

export const allHairVisibilities = {
  ...allHairColorVisibilities,
  ...allHairLengthVisibilities,
  "ahoge": preset.hair,
  "alternate hairstyle": preset.hair,
  "antenna hair": preset.hair,
  "arched bangs": preset.bangs,
  "asymmetrical bangs": preset.bangs,
  "asymmetrical hair": preset.hair,
  "asymmetrical sidelocks": preset.hair,
  "bangs pinned back": preset.bangs,
  "blunt bangs": preset.bangs,
  "blunt ends": preset.hair, // TODO: `blunt bangs ends`
  "bob cut": preset.hair,
  "bow-shaped hair": preset.hair,
  "braid": preset.hair,
  "braided bangs": preset.hair,
  "braided bun": preset.hair,
  "braided ponytail": preset.hair,
  "center-flap bangs": preset.bangs,
  "colored inner hair": preset.hair,
  "cone hair bun": preset.hair,
  "cowlick": preset.bangs,
  "crossed bangs": preset.bangs,
  "crown braid": preset.hair,
  "curly hair": preset.hair,
  "curtained bangs": preset.bangs,
  "diagonal bangs": preset.bangs,
  "double bun": preset.hair,
  "doughnut hair bun": preset.hair,
  "dreadlocks": preset.hair,
  "drill hair": preset.hair,
  "drill sidelocks": preset.hair,
  "dyed bangs": preset.bangs,
  "flipped hair": preset.hair,
  "flower-shaped hair": preset.hair,
  "folded ponytail": preset.hair,
  "frentch braid": preset.hair,
  "front braid": preset.hair,
  "gradient hair": preset.hair,
  "hair between eyes": preset.bangs,
  "hair bun": preset.hair,
  "hair down": preset.hair,
  "hair flaps": preset.hair,
  "hair intakes": preset.bangs,
  "hair over eyes": preset.bangs,
  "hair over one eye": preset.bangs,
  "hair over shoulder": preset.hair,
  "hair pulled back": preset.hair,
  "hair rings": preset.hair,
  "hair slicked back": preset.hair,
  "hair up": preset.hair,
  "half updo": preset.hair,
  "heart ahoge": preset.hair,
  "heart antenna hair": preset.hair,
  "heart hair bun": preset.hair,
  "high ponytail": preset.hair,
  "hime cut": preset.hair,
  "huge ahoge": preset.hair,
  "inverted bob": preset.hair,
  "long bangs": preset.bangs,
  "low ponytail": preset.hair,
  "low twin braids": preset.hair,
  "low twintails": preset.hair,
  "low-braided long hair": preset.hair,
  "low-tied long hair": preset.hair,
  "low-tied sidelocks": preset.hair,
  "messy hair": preset.hair,
  "mizura": preset.hair,
  "multi-tied-hair": preset.hair,
  "multiple braids": preset.hair,
  "one side up": preset.hair,
  "parted bangs": preset.bangs,
  "pixie cut": preset.hair,
  "pointy hair": preset.hair,
  "ponytail": preset.hair,
  "ringlets": preset.hair,
  "short hair with long locks": preset.hair,
  "short ponytail": preset.hair,
  "short twintails": preset.hair,
  "side braid": preset.hair,
  "side ponytail": preset.hair,
  "sidelocks": preset.hair,
  "single braid": preset.hair,
  "single hair bun": preset.hair,
  "single hair intake": preset.bangs,
  "single hair ring": preset.hair,
  "single sidelock": preset.hair,
  "split ponytail": preset.hair,
  "straight hair": preset.hair,
  "swept bangs": preset.bangs,
  "topknot": preset.hair,
  "tri braids": preset.hair,
  "tri tails": preset.hair,
  "triple bun": preset.hair,
  "twin braids": preset.hair,
  "twin drills": preset.hair,
  "twintails": preset.hair,
  "two side up": preset.hair,
  "undercut": preset.hair,
  "wavy hair": preset.hair,
  "wide ponytail": preset.hair,
} as const satisfies Record<HairTag, Visibility>;
