import { HeadOutfitTag } from "../tag-defines/head-outfit.mjs";
import { Visibility } from "../visibility.mjs";

const preset = {
  hair: {
    frontHead: true,
    sideHead: true,
    backHead: true,
    frontBreast: false,
    sideBreast: false,
    backBreast: false,
    frontMidriff: false,
    sideMidriff: false,
    backMidriff: false,
    frontHipAndThigh: false,
    sideHipAndThigh: false,
    backHipAndThigh: false,
    foot: false,
    wristAndHand: false,
    aroundBody: false,
  },
} as const satisfies { [k: string]: Visibility };

const allDistinguishableHeadOutfitVisibilities = {
  "aqua hair bow": preset.hair,
  "black hair bow": preset.hair,
  "blue hair bow": preset.hair,
  "brown hair bow": preset.hair,
  "green hair bow": preset.hair,
  "grey hair bow": preset.hair,
  "orange hair bow": preset.hair,
  "pink hair bow": preset.hair,
  "purple hair bow": preset.hair,
  "red hair bow": preset.hair,
  "white hair bow": preset.hair,
  "yellow hair bow": preset.hair,
  "aqua hair ribbon": preset.hair,
  "black hair ribbon": preset.hair,
  "blue hair ribbon": preset.hair,
  "brown hair ribbon": preset.hair,
  "green hair ribbon": preset.hair,
  "grey hair ribbon": preset.hair,
  "orange hair ribbon": preset.hair,
  "pink hair ribbon": preset.hair,
  "purple hair ribbon": preset.hair,
  "red hair ribbon": preset.hair,
  "white hair ribbon": preset.hair,
  "yellow hair ribbon": preset.hair,
  "jingle bell hair ornament": preset.hair,
  "cable knit hat": preset.hair,
} as const satisfies { [key in HeadOutfitTag]?: Visibility };

const allHairbandColorVisibilities = {
  "red hairband": preset.hair,
  "pink hairband": preset.hair,
  "orange hairband": preset.hair,
  "brown hairband": preset.hair,
  "yellow hairband": preset.hair,
  "green hairband": preset.hair,
  "aqua hairband": preset.hair,
  "blue hairband": preset.hair,
  "purple hairband": preset.hair,
  "black hairband": preset.hair,
  "grey hairband": preset.hair,
  "white hairband": preset.hair,
} as const satisfies { [key in HeadOutfitTag]?: Visibility };

const allHatColorVisibilities = {
  "aqua hat": preset.hair,
  "black hat": preset.hair,
  "blue hat": preset.hair,
  "brown hat": preset.hair,
  "green hat": preset.hair,
  "grey hat": preset.hair,
  "orange hat": preset.hair,
  "pink hat": preset.hair,
  "purple hat": preset.hair,
  "red hat": preset.hair,
  "white hat": preset.hair,
  "yellow hat": preset.hair,
} as const satisfies { [key in HeadOutfitTag]?: Visibility };

export const allHeadOutfitVisibilities = {
  ...allDistinguishableHeadOutfitVisibilities,
  ...allHairbandColorVisibilities,
  ...allHatColorVisibilities,
  "anchor hair ornament": preset.hair,
  "bat hair ornament": preset.hair,
  "bone hair ornament": preset.hair,
  "bow hairband": preset.hair,
  "bridal veil": preset.hair,
  "butterfly hair ornament": preset.hair,
  "cabbie hat": preset.hair,
  "cat hair ornament": preset.hair,
  "character hair ornament": preset.hair,
  "clover hair ornament": preset.hair,
  "coin hair ornament": preset.hair,
  "crescent hair ornament": preset.hair,
  "cross hair ornament": preset.hair,
  "crown": preset.hair,
  "cube hair ornament": preset.hair,
  "d-pad hair ornament": preset.hair,
  "diadem": preset.hair,
  "earrings": preset.hair,
  "fake animal ears": preset.hair,
  "feather hair ornament": preset.hair,
  "fish hair ornament": preset.hair,
  "flower knot": preset.hair,
  "food-themed hair ornament": preset.hair,
  "frilled hairband": preset.hair,
  "frog hair ornament": preset.hair,
  "fur-trimmed headwear": preset.hair,
  "gold earrings": preset.hair,
  "gold hairband": preset.hair,
  "hair beads": preset.hair,
  "hair bell": preset.hair,
  "hair bobbles": preset.hair,
  "hair bow": preset.hair,
  "hair flower": preset.hair,
  "hair ornament": preset.hair,
  "hair ribbon": preset.hair,
  "hair scrunchie": preset.hair,
  "hair stick": preset.hair,
  "hair tie": preset.hair,
  "hairband": preset.hair,
  "hairclip": preset.hair,
  "hairpin": preset.hair,
  "hat": preset.hair,
  "headband": preset.hair,
  "headdress": preset.hair,
  "heart hair ornament": preset.hair,
  "kanzashi": preset.hair,
  "lace-trimmed hairband": preset.hair,
  "leaf hair ornament": preset.hair,
  "lolita hairband": preset.hair,
  "maid headdress": preset.hair,
  "monocle hair ornament": preset.hair,
  "musical note hair ornament": preset.hair,
  "no headwear": preset.hair,
  "pirate hat": preset.hair,
  "pom pom hair ornament": preset.hair,
  "rabbit ears": preset.hair,
  "rabbit hair ornament": preset.hair,
  "santa hat": preset.hair,
  "shark hair ornament": preset.hair,
  "skull hair ornament": preset.hair,
  "snake hair ornament": preset.hair,
  "snowflake hair ornament": preset.hair,
  "star hair ornament": preset.hair,
  "striped hairband": preset.hair,
  "tassel hair ornament": preset.hair,
  "tiara": preset.hair,
  "tress ribbon": preset.hair,
  "two-tone hairband": preset.hair,
  "veil": preset.hair,
  "witch hat": preset.hair,
  "x hair ornament": preset.hair,
} as const satisfies {
  [key in HeadOutfitTag]: Visibility;
};
