const allCarpetColorTags = [
  `aqua carpet`,
  `black carpet`,
  `blue carpet`,
  `brown carpet`,
  `green carpet`,
  `grey carpet`,
  `orange carpet`,
  `pink carpet`,
  `purple carpet`,
  `red carpet`,
  `white carpet`,
  `yellow carpet`,
] as const satisfies string[];

export const allBackgroundTags = [
  ...allCarpetColorTags,
  `alcohol`,
  `amusement park`,
  `bar \\(place\\)`,
  `beach`,
  `bed sheet`,
  `bed`,
  `bedroom`,
  `beer bottle`,
  `beer can`,
  `beer mug`,
  `beer`,
  `bench`,
  `blue background`,
  `blue sky`,
  `blurry background`,
  `book stack`,
  `book`,
  `bookshelf`,
  `brick floor`,
  `building`,
  `cafe`,
  `carpet`,
  `casino`,
  `cave interior`,
  `ceiling light`,
  `ceiling`,
  `chair`,
  `chalkboard`,
  `christmas present`,
  `christmas tree`,
  `christmas`,
  `city lights`,
  `city`,
  `cityscape`,
  `classroom`,
  `cloud`,
  `confetti`,
  `couch`,
  `day`,
  `falling petals`,
  `fence`,
  `floor`,
  `flower`,
  `forest`,
  `garden`,
  `grass`,
  `gym storeroom`,
  `gym`,
  `heart background`,
  `heart`,
  `indoors`,
  `karaoke-box`,
  `karaoke`,
  `lamp`,
  `mat`,
  `moon`,
  `mountain`,
  `night sky`,
  `night`,
  `ocean`,
  `office chair`,
  `office`,
  `on bed`,
  `on bench`,
  `on chair`,
  `on couch`,
  `on desk`,
  `on floor`,
  `on grass`,
  `on ground`,
  `on roof`,
  `on stool`,
  `on vehicle`,
  `onsen`,
  `orange sky`,
  `outdoors`,
  `palm tree`,
  `partially submerged`,
  `petals`,
  `pillow`,
  `pink background`,
  `playing card`,
  `pool`,
  `poolside`,
  `race vehicle`,
  `racecar`,
  `racetrack`,
  `red background`,
  `red curtains`,
  `road`,
  `rock`,
  `rooftop`,
  `school chair`,
  `school desk`,
  `simple background`,
  `spoken heart`,
  `steam`,
  `steaming body`,
  `stool`,
  `sunbeam`,
  `sunlight`,
  `sunset`,
  `sweat`,
  `tatami`,
  `tennis court`,
  `tennis net`,
  `tire`,
  `vaulting horse`,
  `volleyball net`,
  `volleyball`,
  `water`,
  `wedding`,
  `wet`,
  `white background`,
  `window`,
  `wooden chair`,
  `wooden floor`,
  `yellow background`,
] as const satisfies readonly string[];
export type BackgroundTag = (typeof allBackgroundTags)[number];
