export const allBackgroundTags = [
  `amusement park`,
  `beach`,
  `bed sheet`,
  `bed`,
  `bedroom`,
  `blue background`,
  `blue sky`,
  `blurry background`,
  `brick floor`,
  `cafe`,
  `casino`,
  `cave interior`,
  `ceiling`,
  `chalkboard`,
  `christmas present`,
  `christmas tree`,
  `christmas`,
  `city lights`,
  `city`,
  `cityscape`,
  `classroom`,
  `confetti`,
  `couch`,
  `day`,
  `falling petals`,
  `floor`,
  `forest`,
  `garden`,
  `grass`,
  `heart background`,
  `heart`,
  `indoors`,
  `karaoke-box`,
  `karaoke`,
  `lamp`,
  `moon`,
  `mountain`,
  `night sky`,
  `night`,
  `ocean`,
  `office`,
  `orange sky`,
  `outdoors`,
  `partially submerged`,
  `petals`,
  `pillow`,
  `pink background`,
  `playing card`,
  `pool`,
  `poolside`,
  `red background`,
  `rock`,
  `rooftop`,
  `school chair`,
  `school desk`,
  `simple background`,
  `spoken heart`,
  `steam`,
  `steaming body`,
  `sunset`,
  `sweat`,
  `wedding`,
  `wet`,
  `white background`,
  `window`,
  `wooden floor`,
  `on bed`,
  `on couch`,
] as const satisfies readonly string[];
export type BackgroundTag = (typeof allBackgroundTags)[number];
