export const allBackgroundTags = [
  `amusement park`,
  `beach`,
  `bed sheet`,
  `bed`,
  `bedroom`,
  `blue background`,
  `blue sky`,
  `blurry background`,
  `brick floor`,
  `building`,
  `cafe`,
  `casino`,
  `cave interior`,
  `ceiling`,
  `chalkboard`,
  `christmas present`,
  `christmas tree`,
  `christmas`,
  `city lights`,
  `city`,
  `cityscape`,
  `classroom`,
  `confetti`,
  `couch`,
  `day`,
  `falling petals`,
  `floor`,
  `forest`,
  `garden`,
  `grass`,
  `gym storeroom`,
  `gym`,
  `heart background`,
  `heart`,
  `indoors`,
  `karaoke-box`,
  `karaoke`,
  `lamp`,
  `mat`,
  `moon`,
  `mountain`,
  `night sky`,
  `night`,
  `ocean`,
  `office`,
  `on bed`,
  `on couch`,
  `orange sky`,
  `outdoors`,
  `palm tree`,
  `partially submerged`,
  `petals`,
  `pillow`,
  `pink background`,
  `playing card`,
  `pool`,
  `poolside`,
  `red background`,
  `road`,
  `rock`,
  `rooftop`,
  `school chair`,
  `school desk`,
  `simple background`,
  `spoken heart`,
  `steam`,
  `steaming body`,
  `sunset`,
  `sweat`,
  `vaulting horse`,
  `volleyball net`,
  `volleyball`,
  `wedding`,
  `wet`,
  `white background`,
  `window`,
  `wooden floor`,
  `yellow background`,
] as const satisfies readonly string[];
export type BackgroundTag = (typeof allBackgroundTags)[number];

// TODO: Add test that emits warn if array is not sorted.
