import { getKeys } from "../utility.mjs";

export const allDistinguishableBodyTags = {
  "aqua short tail": `aqua tail`,
  "black short tail": `black tail`,
  "blue short tail": `blue tail`,
  "brown short tail": `brown tail`,
  "green short tail": `green tail`,
  "grey short tail": `grey tail`,
  "orange short tail": `orange tail`,
  "pink short tail": `pink tail`,
  "purple short tail": `purple tail`,
  "red short tail": `red tail`,
  "white short tail": `white tail`,
  "yellow short tail": `yellow tail`,
  "aqua long tail": `aqua tail`,
  "black long tail": `black tail`,
  "blue long tail": `blue tail`,
  "brown long tail": `brown tail`,
  "green long tail": `green tail`,
  "grey long tail": `grey tail`,
  "orange long tail": `orange tail`,
  "pink long tail": `pink tail`,
  "purple long tail": `purple tail`,
  "red long tail": `red tail`,
  "white long tail": `white tail`,
  "yellow long tail": `yellow tail`,
} as const satisfies { [k in string]: string };

export const allBodyTags = [
  ...getKeys(allDistinguishableBodyTags),
  `animal ear fluff`,
  `animal ears`,
  `cat ears`,
  `cat girl`,
  `cat tail`,
  `curvy`,
  `dark skin`,
  `dark-skinned female`,
  `demon tail`,
  `dog ears`,
  `dog girl`,
  `dog tail`,
  `elf`,
  `fox ears`,
  `fox girl`,
  `fox tail`,
  `gyaru`,
  `loli`,
  `mature female`,
  `pointy ears`,
  `rabbit ears`,
  `rabbit girl`,
  `rabbit tail`,
  `tail`,
  `tan`,
  `thick thighs`,
  `toned`,
  `wide hips`,
] as const satisfies readonly string[];
export type BodyTag = (typeof allBodyTags)[number];
