export const allCharacterNameTags = [
  `aisha greyrat`,
  `aiz wallenstein`,
  `akemi homura`,
  `akoya matama`,
  `alicia edelcia`,
  `alpha \\(kage no jitsuryokusha ni naritakute!\\)`,
  `angelina kudou shields`,
  `aqua \\(konosuba\\)`,
  `arona \\(blue archive\\)`,
  `ayane \\(blue archive\\)`,
  `beta \\(kage no jitsuryokusha ni naritakute!\\)`,
  `cecilia alcott`,
  `celia claire`,
  `celistia ralgris`,
  `charlotte dunois`,
  `charlotte e\\. yeager`,
  `chiba erika`,
  `chitanda eru`,
  `chiyoda momo`,
  `chloe von einzbern \\(beast style\\)`,
  `chloe von einzbern`,
  `chris \\(konosuba\\)`,
  `cow girl \\(goblin slayer!\\)`,
  `darkness \\(konosuba\\)`,
  `delta \\(kage no jitsuryokusha ni naritakute!\\)`,
  `eila ilmatar juutilainen`,
  `eina tulle`,
  `emilia \\(re:zero\\)`,
  `enome`,
  `epsilon \\(kage no jitsuryokusha ni naritakute!\\)`,
  `erica hartmann`,
  `eris greyrat`,
  `eta \\(kage no jitsuryokusha ni naritakute!\\)`,
  `francesca lucchini`,
  `fujimiya sumika \\(isekai ojisan\\)`,
  `fujiwara chika`,
  `gamma \\(kage no jitsuryokusha ni naritakute!\\)`,
  `gene \\(pso2\\)`,
  `gertrud barkhorn`,
  `gina boyd`,
  `guild girl \\(goblin slayer!\\)`,
  `hanabata nohkins`,
  `hattori shizuka`,
  `hayasaka ai`,
  `hestia \\(danmachi\\)`,
  `high elf archer \\(goblin slayer!\\)`,
  `hinata kaho`,
  `hinatsuki mikan`,
  `hinatsuru ai`,
  `hitamu kyan`,
  `hoshikawa mafuyu`,
  `hoshino \\(blue archive\\)`,
  `hoto cocoa`,
  `huang lingyin`,
  `ichijou hotaru`,
  `iijima yun`,
  `iino miko`,
  `illyasviel von einzbern \\(beast style\\)`,
  `illyasviel von einzbern`,
  `inoue takina`,
  `izumi noel`,
  `izumi noel`,
  `izumi sagiri`,
  `izuna \\(blue archive\\)`,
  `izuna \\(swimsuit\\) \\(blue archive\\)`,
  `jinno megumi`,
  `jouga maya`,
  `kafuu chino`,
  `kaname madoka`,
  `kirihime yoruka`,
  `kirima syaro`,
  `kitayama shizuku`,
  `koborii \\(amaburi\\)`,
  `konjiki no yami`,
  `kotegawa yui`,
  `krulcifer einfolk`,
  `kurosaki mea`,
  `lala satalin deviluke`,
  `latifa fleuranza`,
  `laura bodewig`,
  `liliruca arde`,
  `lilishka`,
  `lillia greyrat`,
  `lisesharte atismata`,
  `loco musica`,
  `lynette bishop`,
  `mabel raybert`,
  `maidena angers`,
  `maple \\(bofuri\\)`,
  `megumin`,
  `miki sayaka`,
  `minagi hiyori`,
  `minagi koharu`,
  `minna-dietlinde wilcke`,
  `mitsui honoka`,
  `miyafuji yoshika`,
  `miyu edelfelt \\(beast style\\)`,
  `miyu edelfelt`,
  `momo velia deviluke`,
  `muse \\(amaburi\\)`,
  `nana asta deviluke`,
  `nanami yachiyo`,
  `natsu megumi`,
  `nishikigi chisato`,
  `norn greyrat`,
  `ogiwara sayu`,
  `orimura chifuyu`,
  `perrine h\\. clostermann`,
  `philuffy aingram`,
  `priestess \\(goblin_slayer!\\)`,
  `ram \\(re:zero\\)`,
  `reisalin stout`,
  `rem \\(re:zero\\)`,
  `roxy migurdia`,
  `rumia tingel`,
  `ryu lion`,
  `saegusa mayumi`,
  `sairenji haruna`,
  `sakamoto mio`,
  `saki \\(blue archive\\)`,
  `saki \\(swimsuit\\) \\(blue archive\\)`,
  `sakura hibiki`,
  `sakura kyoko`,
  `sakura kyouko`,
  `sakura nene`,
  `sakuranomiya maika`,
  `salama \\(amaburi\\)`,
  `sally \\(bofuri\\)`,
  `sanjouno haruhime`,
  `sanya v\\. litvyak`,
  `sarashiki kanzashi`,
  `sarashiki tatenashi`,
  `senju muramasa`,
  `sento isuzu`,
  `serika \\(blue archive\\)`,
  `shiba miyuki`,
  `shibata mizuki`,
  `shiina mahiru \\(otonari no tenshi-sama\\)`,
  `shinoda hajime`,
  `shinomiya kaguya`,
  `shinonono houki`,
  `shirogane kei`,
  `shiroko \\(blue archive\\)`,
  `shiroko \\(cycling\\) \\(blue archive\\)`,
  `shiroko \\(swimsuit\\) \\(blue archive\\)`,
  `shokuhou misaki`,
  `souryuuin akemi`,
  `sui \\(isekai ojisan\\)`,
  `suzukaze aoba`,
  `sword maiden`,
  `sylphiette \\(mushoku tensei\\)`,
  `sylphy \\(amaburi\\)`,
  `tachibana satomi`,
  `takasago tomoe`,
  `takimoto hifumi`,
  `tamaki iroha`,
  `taneshima popura`,
  `tedeza rize`,
  `tohsaka rin`,
  `tokishikko dana`,
  `tomoe mami`,
  `tooyama rin`,
  `towa \\(tenshi-tsuki\\)`,
  `tsuribuka hisui`,
  `tsutsumi tsumugi`,
  `uehara ayaka`,
  `ujimatsu chiya`,
  `wiz \\(konosuba\\)`,
  `yagami kou`,
  `yamada elf`,
  `yamada maya \\(infinite stratos\\)`,
  `yashajin ai`,
  `yor briar`,
  `yoruka kirihime`,
  `yoshida yuuko \\(machikado mazoku\\)`,
  `yoshinaga koi`,
  `yui kotegawa`,
  `yunyun \\(konosuba\\)`,
  `yunyun \\(konosuba\\)`,
  `yuuka \\(blue archive\\)`,
  `yuuka \\(track\\) \\(blue archive\\)`,
  `zenith greyrat`,
  `zeta \\(kage no jitsuryokusha ni naritakute!\\)`,
] as const satisfies readonly string[];
export type CharacterNameTag = (typeof allCharacterNameTags)[number];
