export const allCharacterName = [
  `aiz wallenstein`,
  `akemi homura`,
  `akoya matama`,
  `alicia edelcia`,
  `alpha \\(kage no jitsuryokusha ni naritakute!\\)`,
  `beta \\(kage no jitsuryokusha ni naritakute!\\)`,
  `cecilia alcott`,
  `celistia ralgris`,
  `charlotte dunois`,
  `chiba erika`,
  `chloe von einzbern \\(beast style\\)`,
  `chloe von einzbern`,
  `delta \\(kage no jitsuryokusha ni naritakute!\\)`,
  `eina tulle`,
  `emilia \\(re:zero\\)`,
  `epsilon \\(kage no jitsuryokusha ni naritakute!\\)`,
  `eta \\(kage no jitsuryokusha ni naritakute!\\)`,
  `fujimiya sumika \\(isekai ojisan\\)`,
  `fujiwara chika`,
  `gamma \\(kage no jitsuryokusha ni naritakute!\\)`,
  `gene \\(pso2\\)`,
  `gina boyd`,
  `hayasaka ai`,
  `hestia \\(danmachi\\)`,
  `hoto cocoa`,
  `huang lingyin`,
  `ichijou hotaru`,
  `iino miko`,
  `illyasviel von einzbern \\(beast style\\)`,
  `illyasviel von einzbern`,
  `inoue takina`,
  `jouga maya`,
  `kafuu chino`,
  `kaname madoka`,
  `kirihime yoruka`,
  `kirima syaro`,
  `kitayama shizuku`,
  `koborii \\(amaburi\\)`,
  `konjiki no yami`,
  `kotegawa yui`,
  `krulcifer einfolk`,
  `kurosaki mea`,
  `lala satalin deviluke`,
  `latifa fleuranza`,
  `laura bodewig`,
  `liliruca arde`,
  `lisesharte atismata`,
  `loco musica`,
  `mabel raybert`,
  `miki sayaka`,
  `mitsui honoka`,
  `miyu edelfelt \\(beast style\\)`,
  `miyu edelfelt`,
  `momo velia deviluke`,
  `muse \\(amaburi\\)`,
  `nana asta deviluke`,
  `nanami yachiyo`,
  `natsu megumi`,
  `nishikigi chisato`,
  `orimura chifuyu`,
  `philuffy aingram`,
  `ram \\(re:zero\\)`,
  `rem \\(re:zero\\)`,
  `ryu lion`,
  `saegusa mayumi`,
  `sairenji haruna`,
  `sakura hibiki`,
  `sakura kyoko`,
  `sakura kyouko`,
  `salama \\(amaburi\\)`,
  `sanjouno haruhime`,
  `sento isuzu`,
  `shiba miyuki`,
  `shibata mizuki`,
  `shinomiya kaguya`,
  `shinonono houki`,
  `shirogane kei`,
  `shokuhou misaki`,
  `souryuuin akemi`,
  `sui \\(isekai ojisan\\)`,
  `suzukaze aoba`,
  `sylphy \\(amaburi\\)`,
  `tachibana satomi`,
  `takimoto hifumi`,
  `tamaki iroha`,
  `tedeza rize`,
  `tohsaka rin`,
  `tomoe mami`,
  `uehara ayaka`,
  `ujimatsu chiya`,
  `yamada maya \\(infinite stratos\\)`,
  `yor briar`,
  `yoruka kirihime`,
  `yui kotegawa`,
  `zeta \\(kage no jitsuryokusha ni naritakute!\\)`,
] as const satisfies readonly string[];
export type CharacterNameTag = (typeof allCharacterName)[number];
