export const allEmotionTags = [
  `;\\)`,
  `;d`,
  `;o`,
  `:\\)`,
  `:d`,
  `:o`,
  `!`,
  `?`,
  `angry`,
  `blush`,
  `closed mouth`,
  `confused`,
  `doyagao`,
  `embarrassed`,
  `expressionless`,
  `flustered`,
  `grin`,
  `half-closed eyes`,
  `heart`,
  `heavy breathing`,
  `light smile`,
  `moaning`,
  `naughty face`,
  `nervous`,
  `nose blush`,
  `one eye closed`,
  `open mouth`,
  `parted lips`,
  `puff of air`,
  `scowl`,
  `seductive smile`,
  `smile`,
  `smug`,
  `speech bubble`,
  `spoken heart`,
  `spoken object`,
  `surprised`,
  `torogao`,
  `v-shaped eyebrows`,
] as const satisfies readonly string[];
export type EmotionTag = (typeof allEmotionTags)[number];
