const allEyewearColorTags = [
  `aqua-framed eyewear`,
  `black-framed eyewear`,
  `blue-framed eyewear`,
  `brown-framed eyewear`,
  `green-framed eyewear`,
  `grey-framed eyewear`,
  `orange-framed eyewear`,
  `pink-framed eyewear`,
  `purple-framed eyewear`,
  `red-framed eyewear`,
  `white-framed eyewear`,
  `yellow-framed eyewear`,
] as const satisfies readonly string[];

const allTintedEyewearColorTags = [
  `blue-tinted eyewear`,
  `green-tinted eyewear`,
  `orange-tinted eyewear`,
  `pink-tinted eyewear`,
  `purple-tinted eyewear`,
  `red-tinted eyewear`,
  `yellow-tinted eyewear`,
] as const satisfies readonly string[];

export const allGlassesTags = [
  ...allEyewearColorTags,
  ...allTintedEyewearColorTags,
  `aviator sunglasses`,
  `bespectacled`,
  `coke-bottle glasses`,
  `diving mask`,
  `eyepatch`,
  `eyewear on head`,
  `eyewear on headwear`,
  `eyewear strap`,
  `glasses`,
  `goggles`,
  `heart-shaped eyewear`,
  `monocle`,
  `no eyewear`,
  `opaque glasses`,
  `over-rim eyewear`,
  `pince-nez`,
  `rectangular eyewear`,
  `rimless eyewear`,
  `round eyewear`,
  `scouter`,
  `semi-rimless eyewear`,
  `star-shaped eyewear`,
  `sunglasses`,
  `teardrop-framed glasses`,
  `tinted eyewear`,
  `under-rim eyewear`,
] as const satisfies readonly string[];
export type GlassesTag = (typeof allGlassesTags)[number];
