export const allPoseTags = [
  `all fours`,
  `arm up`,
  `arms behind head`,
  `arms up`,
  `ass focus`,
  `backlighting`,
  `bouquet`,
  `breasts`,
  `cheering`,
  `close-up`,
  `clothes lift`,
  `contrapposto`,
  `cowboy shot`,
  `double v`,
  `dress lift`,
  `from above`,
  `from behind`,
  `from below`,
  `from side`,
  `full body`,
  `grabbing own breast`,
  `grabbing`,
  `hand up`,
  `hands on lap`,
  `hands on own cheek`,
  `hands on own chest`,
  `hands on own face`,
  `hands on own hips`,
  `hands on own knees`,
  `hands on own thighs`,
  `hands up`,
  `head rest`,
  `heart hands`,
  `holding bouquet`,
  `holding microphone`,
  `holding pom poms`,
  `incoming hug`,
  `index finger raised`,
  `kneeling`,
  `leaning forward`,
  `leg up`,
  `legs up`,
  `looking ahead`,
  `looking at viewer`,
  `looking away`,
  `looking back`,
  `looking down`,
  `looking up`,
  `lying`,
  `microphone`,
  `on back`,
  `on bed`,
  `on side`,
  `on stomach`,
  `paw pose`,
  `pom pom \\(cheerleading\\)`,
  `portrait`,
  `profile`,
  `reaching towards viewer`,
  `shushing`,
  `singing`,
  `sitting`,
  `skirt lift`,
  `spread legs`,
  `squatting`,
  `standing`,
  `the pose`,
  `thighs`,
  `twisted torso`,
  `undressing`,
  `upper body`,
  `upturned eyes`,
  `v`,
  `wariza`,
] as const satisfies readonly string[];
export type PoseTag = (typeof allPoseTags)[number];
