export const allSeriesNameTags = [
  `amagi brilliant park`,
  `assault lily`,
  `blend s`,
  `bocchi the rock!`,
  `boku no hero academia`,
  `dumbbell nan kilo moteru?`,
  `dungeon ni deai wo motomeru no wa machigatteiru darou ka`,
  `fate/kaleid liner prisma illya`,
  `fate/stay night`,
  `fate/unlimited blade works`,
  `futoku no guild`,
  `gochuumon wa usagi desu ka?`,
  `gridman universe`,
  `hige wo soru\\. soshite joshikousei wo hirou\\.`,
  `infinite stratos`,
  `isekai nonbiri nouka`,
  `isekai ojisan`,
  `kage no jitsuryokusha ni naritakute!`,
  `kaguya-sama wa kokurasetai ~tensai-tachi no renai zunousen~`,
  `kanojo mo kanojo`,
  `kono subarashii sekai ni shukufuku wo!`,
  `lycoris recoil`,
  `machikado mazoku`,
  `magia record: mahou shoujo madoka magica gaiden`,
  `mahou shoujo madoka magica`,
  `mahou shoujo ni akogarete`,
  `mahouka koukou no rettousei`,
  `majo no tabitabi`,
  `megami-ryou no ryoubo-kun`,
  `mushoku tensei`,
  `new game!`,
  `non non biyori`,
  `otonari no tenshi-sama ni itsu no mani ka dame ningen ni sarete ita ken`,
  `phantasy star online 2`,
  `rakudai kishi no cavalry`,
  `re:zero kara hajimeru isekai seikatsu`,
  `rokudenashi majutsu koushi to akashic record`,
  `ryuuou no oshigoto!`,
  `saenai heroine no sodatekata`,
  `saijaku muhai no bahamut`,
  `seiken gakuin no maken tsukai`,
  `shy \\(series\\)`,
  `sono bisque doll wa koi wo suru`,
  `spy x family`,
  `ssss\\.dynazenon`,
  `ssss\\.gridman`,
  `sword art online`,
  `to love-ru darkness`,
  `to love-ru`,
  `toaru kagaku no railgun`,
  `working!!`,
] as const satisfies readonly string[];
export type SeriesNameTag = (typeof allSeriesNameTags)[number];
