import { EmotionKey, EmotionType } from "./emotions.mjs";

export type EmotionProbabilitiesAtEmotionType = Record<
  EmotionType,
  Record<EmotionKey, number>
>;

export const emotionProbabilitiesAtEmotionType = {
  cute: {
    "smile-profile": 1.5,
    "smile": 1.5,
    "light-smile-profile": 0.5,
    "light-smile": 0.5,
    "expressionless": 1.0,
    "surprised": 1.0,
    "confused": 1.0,
    "embarrassed": 1.0,
    "seductive-smile": 1.0,
    "embarrassed-scowl": 1.0,
    "angry": 1.0,
    "grin": 0.5,
    "doyagao": 1.0,
  },
  serious: {
    "smile-profile": 0.5,
    "smile": 0.5,
    "light-smile-profile": 1.5,
    "light-smile": 1.5,
    "expressionless": 1.5,
    "surprised": 0.8,
    "confused": 0.8,
    "embarrassed": 1.0,
    "seductive-smile": 1.0,
    "embarrassed-scowl": 1.5,
    "angry": 0.8,
    "grin": 0.5,
    "doyagao": 0.5,
  },
  tsundere: {
    "smile-profile": 1.0,
    "smile": 1.0,
    "light-smile-profile": 1.0,
    "light-smile": 1.0,
    "expressionless": 1.0,
    "surprised": 1.0,
    "confused": 1.0,
    "embarrassed": 1.0,
    "seductive-smile": 1.0,
    "embarrassed-scowl": 2.0,
    "angry": 1.0,
    "grin": 0.5,
    "doyagao": 0.8,
  },
  emotionless: {
    "smile-profile": 1.0,
    "smile": 1.0,
    "light-smile-profile": 1.0,
    "light-smile": 1.0,
    "expressionless": 3.0,
    "surprised": 1.0,
    "confused": 1.0,
    "embarrassed": 1.0,
    "seductive-smile": 1.0,
    "embarrassed-scowl": 0.5,
    "angry": 0.5,
    "grin": 0.5,
    "doyagao": 0.5,
  },
  mesugaki: {
    "smile-profile": 1.0,
    "smile": 1.0,
    "light-smile-profile": 1.0,
    "light-smile": 1.0,
    "expressionless": 1.0,
    "surprised": 1.0,
    "confused": 1.0,
    "embarrassed": 1.0,
    "seductive-smile": 1.0,
    "embarrassed-scowl": 1.0,
    "angry": 1.0,
    "grin": 3.0,
    "doyagao": 1.0,
  },
} as const satisfies EmotionProbabilitiesAtEmotionType;
