import type { OutfitDefine } from "../outfits.mjs";

export const catLingerie = (): OutfitDefine =>
  ({
    lora: null,
    loraOutfitTriggerWordEntries: [],
    outfitEntries: [
      `choker`,
      `neck jingle bell -> jingle bell`,
      `cat lingerie`,
      `underwear`,
      `underwear only`,
      `bra`,
      `black bra`,
      `cat cutout`,
      `cleavage cutout`,
      `cleavage cutout -> clothing cutout`,
      `frilled bra`,
      `breasts skindentation -> skindentation`,
      `panties`,
      `black panties`,
      `cat ear panties`,
      `side-tie panties`,
      `fake animal ears`,
      `cat ears`,
      `animal ear fluff`,
      `cat tail`,
      `black long tail -> black tail`,
      `paw gloves`,
      `thighhighs`,
      `black thighhighs`,
      `thighs skindentation -> skindentation`,
    ],
    specialVisibility: {
      armpits: true,
      hangingBreasts: true,
      tautClothes: false,
      cleavage: true,
      sideboob: true,
      backboob: true,
      underboobLevel: `only from below`,
      zettaiRyouiki: false,
      insideOfThighs: true,
    },
    upskirt: null,
    whenRemoveShoes: null,
  }) as const satisfies OutfitDefine;
